### PR TITLE
Resizable editors

### PR DESCRIPTION
**Pull request by joprice**
This adds the ability to resize the editors by dragging on the middle gutter.

It also fixes an issue where the error transition causes the screen to flicker and sets the lines to wrap.

### CODE REVIEW

**Comment by afraser** [comment]
Any reason you're not merging this? @snookca

**Comment by Anaphase** [comment]
Last I heard, this project was abandoned by it's creator.

**Comment by snookca** [comment]
Yeah, I haven't been maintaining this. I couldn't tell you if this even compiles into an add-on properly anymore. I could merge this but I haven't tested or code reviewed it. If someone wants to do that, I'll gladly merge it.

**Comment by joprice** [comment]
I'm happy to take over as maintainer.

**Comment by thomasf1** [comment]
Hey guys.... Because the Chrome Extension stopped working for me and the project seems abandoned I´ve forked it, improved it a bit (added error messages from JS execution)... I hope that helps everyone else having issues with it :) https://github.com/colldo/CoffeeConsole2

**Pull request closed without merging**
